<a href="https://colab.research.google.com/github/rani-sikdar/Advanced-NLP/blob/main/Text_Classifier_Markov_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget -nc https://raw.githubusercontent.com/lazyprogrammer/machine_learning_examples/master/hmm_class/edgar_allan_poe.txt
!wget -nc https://raw.githubusercontent.com/lazyprogrammer/machine_learning_examples/master/hmm_class/robert_frost.txt

--2025-04-12 06:01:06--  https://raw.githubusercontent.com/lazyprogrammer/machine_learning_examples/master/hmm_class/edgar_allan_poe.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26622 (26K) [text/plain]
Saving to: ‘edgar_allan_poe.txt’

edgar_allan_poe.txt 100%[===================>]  26.00K  --.-KB/s    in 0.002s  

2025-04-12 06:01:07 (11.1 MB/s) - ‘edgar_allan_poe.txt’ saved [26622/26622]

--2025-04-12 06:01:07--  https://raw.githubusercontent.com/lazyprogrammer/machine_learning_examples/master/hmm_class/robert_frost.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP re

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import string
from sklearn.model_selection import train_test_split

In [3]:
input_files=[
    'edgar_allan_poe.txt',
    'robert_frost.txt'
]

In [4]:
!head edgar_allan_poe.txt

LO! Death hath rear'd himself a throne
In a strange city, all alone,
Far down within the dim west
Where the good, and the bad, and the worst, and the best,
Have gone to their eternal rest.
 
There shrines, and palaces, and towers
Are not like any thing of ours
Oh no! O no! ours never loom
To heaven with that ungodly gloom!


In [5]:
!head robert_frost.txt

Two roads diverged in a yellow wood,
And sorry I could not travel both
And be one traveler, long I stood
And looked down one as far as I could
To where it bent in the undergrowth; 

Then took the other, as just as fair,
And having perhaps the better claim
Because it was grassy and wanted wear,
Though as for that the passing there


In [12]:
# collect data into lists
input_texts =[]
labels =[]

for label, x in enumerate(input_files):
  print("{} corresponds to label {}".format(x,label))

  for line in open(x):
    line = line.rstrip().lower()
    # print(line)

    if line:
      # remove punctuation
      line = line.translate(str.maketrans('', '', string.punctuation))
      # print(line)
      input_texts.append(line)
      labels.append(label)

edgar_allan_poe.txt corresponds to label 0
robert_frost.txt corresponds to label 1


In [14]:
input_texts[1:10], labels[1:10]

(['in a strange city all alone',
  'far down within the dim west',
  'where the good and the bad and the worst and the best',
  'have gone to their eternal rest',
  'there shrines and palaces and towers',
  'are not like any thing of ours',
  'oh no o no ours never loom',
  'to heaven with that ungodly gloom',
  'timeeaten towers that tremble not'],
 [0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
train_text, test_text, ytrain, ytest = train_test_split(input_texts, labels)

In [16]:
len(ytrain), len(ytest)

(1615, 539)

In [17]:
train_text[:10], ytrain[:10]

(['of getting home again because',
  'up from the tangle of withered weeds',
  'the playthings in the playhouse of the children',
  'among the raspberries and hew and shape it',
  'while from the high towers of the town',
  'and better defeat almost',
  'though not yet light',
  'i walked down alone sunday after church',
  'ill show you how she had her sills extended',
  'you never saw this room before a show'],
 [1, 1, 1, 1, 0, 1, 1, 1, 1, 1])

In [18]:
# convert text to index for matrix
idx =1 # act as a current index as we loop thoruhg matrix
word2idx = {'<unk' : 0 }

In [19]:
# populate word2idx
for text in train_text:
  tokens = text.split()
  for token in tokens:
    if token not in word2idx:
      word2idx[token] =idx
      idx += 1

In [20]:
word2idx

{'<unk': 0,
 'of': 1,
 'getting': 2,
 'home': 3,
 'again': 4,
 'because': 5,
 'up': 6,
 'from': 7,
 'the': 8,
 'tangle': 9,
 'withered': 10,
 'weeds': 11,
 'playthings': 12,
 'in': 13,
 'playhouse': 14,
 'children': 15,
 'among': 16,
 'raspberries': 17,
 'and': 18,
 'hew': 19,
 'shape': 20,
 'it': 21,
 'while': 22,
 'high': 23,
 'towers': 24,
 'town': 25,
 'better': 26,
 'defeat': 27,
 'almost': 28,
 'though': 29,
 'not': 30,
 'yet': 31,
 'light': 32,
 'i': 33,
 'walked': 34,
 'down': 35,
 'alone': 36,
 'sunday': 37,
 'after': 38,
 'church': 39,
 'ill': 40,
 'show': 41,
 'you': 42,
 'how': 43,
 'she': 44,
 'had': 45,
 'her': 46,
 'sills': 47,
 'extended': 48,
 'never': 49,
 'saw': 50,
 'this': 51,
 'room': 52,
 'before': 53,
 'a': 54,
 'then': 55,
 'make': 56,
 'yourself': 57,
 'at': 58,
 'only': 59,
 'field': 60,
 'bill': 61,
 'unthoughtlike': 62,
 'thoughts': 63,
 'that': 64,
 'are': 65,
 'souls': 66,
 'thought': 67,
 'pushed': 68,
 'myself': 69,
 'upstairs': 70,
 'hadnt': 71,
 'foun

In [21]:
len(word2idx)

2512

In [22]:
# convert data into integer format
train_text_int =[]
test_text_int =[]

for text in train_text:
  tokens = text.split()
  line_as_int = [word2idx[token] for token in tokens]
  train_text_int.append(line_as_int)


for text in test_text:
  tokens = text.split()
  line_as_int = [word2idx.get(token,0) for token in tokens]
  test_text_int.append(line_as_int)


In [23]:
train_text_int[:5]

[[1, 2, 3, 4, 5],
 [6, 7, 8, 9, 1, 10, 11],
 [8, 12, 13, 8, 14, 1, 8, 15],
 [16, 8, 17, 18, 19, 18, 20, 21],
 [22, 7, 8, 23, 24, 1, 8, 25]]

In [24]:
test_text_int[:5]

[[75, 449, 8, 981, 130, 0],
 [33, 1292, 8, 329, 2449, 0, 259],
 [30, 0, 916, 207, 0, 18, 0],
 [8, 1259, 989, 436, 385, 686, 113, 123, 221, 222],
 [90, 335, 475, 64, 0, 1870, 818]]

In [26]:
# initilaize A and pi matrices -  for both classes
import numpy as np
V = len(word2idx) # vocalblury size

A0 = np.ones((V,V))
pi0= np.ones(V)


A1 = np.ones((V,V))
pi1= np.ones(V)

In [27]:
# compute counts for A and pi
def compute_counts(text_as_int, A, pi):

  for tokens in text_as_int:
    last_idx = None
    for idx in tokens:
      if last_idx is None:
        # it's the first word in a sentence
        pi[idx] += 1
      else:
        # the last word exists, so count a transition
        A[last_idx, idx] += 1

      # update last idx
      last_idx = idx


compute_counts([ t for t,y in zip(train_text_int, ytrain) if y==0], A0, pi0 )
compute_counts([ t for t,y in zip(train_text_int, ytrain) if y==1], A1, pi1 )

In [28]:
A0

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [29]:
A1

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 2., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [30]:
# normalize A and pi so they are valid probability matrices
A0 /= A0.sum(axis=1, keepdims=True)
pi0 /= pi0.sum()

A1 /= A1.sum(axis=1, keepdims=True)
pi1 /= pi1.sum()

In [31]:
# log A and pi since we don't need the actual probs
logA0 = np.log(A0)
logpi0 = np.log(pi0)

logA1 = np.log(A1)
logpi1 = np.log(pi1)

In [34]:
# compute priors
count0 = sum(y == 0 for y in ytrain) #samples belongs to class 0
count1 = sum(y == 1 for y in ytrain) #samples belongs to class 1
total = len(ytrain)
#  compute priror probablites p0 & p1
p0 = count0 / total
p1 = count1 / total
logp0 = np.log(p0)
logp1 = np.log(p1)
p0, p1

(0.32941176470588235, 0.6705882352941176)

In [35]:
# build a classifier
class Classifier:
  def __init__(self, logAs, logpis, logpriors):
    self.logAs = logAs
    self.logpis = logpis
    self.logpriors = logpriors
    self.K = len(logpriors) # number of classes

  def _compute_log_likelihood(self, input_, class_):
    logA = self.logAs[class_]
    logpi = self.logpis[class_]

    last_idx = None
    logprob = 0
    for idx in input_:
      if last_idx is None:
        # it's the first token
        logprob += logpi[idx]
      else:
        logprob += logA[last_idx, idx]

      # update last_idx
      last_idx = idx

    return logprob

  def predict(self, inputs):
    predictions = np.zeros(len(inputs))
    for i, input_ in enumerate(inputs):
      posteriors = [self._compute_log_likelihood(input_, c) + self.logpriors[c] \
             for c in range(self.K)]
      pred = np.argmax(posteriors)
      predictions[i] = pred
    return predictions

In [36]:
# each array must be in order since classes are assumed to index these lists
clf = Classifier([logA0, logA1], [logpi0, logpi1], [logp0, logp1])

In [38]:
Ptrain = clf.predict(train_text_int)
print(f"Train acc: {np.mean(Ptrain == ytrain)}")

Train acc: 0.9944272445820433


In [41]:
Ptest = clf.predict(test_text_int)
print(f"Test acc: {np.mean(Ptest == ytest)}")

Test acc: 0.8181818181818182


In [46]:
from sklearn.metrics import confusion_matrix, f1_score

cm_train = confusion_matrix(ytrain, Ptrain)
cm_train

array([[ 523,    9],
       [   0, 1083]])

In [47]:
cm_test = confusion_matrix(ytest, Ptest)
cm_test

array([[ 99,  87],
       [ 11, 342]])

In [48]:
f1_score(ytrain, Ptrain)

0.9958620689655172

In [49]:
f1_score(ytest, Ptest)

0.8746803069053708